define([], function () {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    WaitListGeneration: 'Please wait..., Forums Hooks lists will be generated soon',
    Name: "Name",
    TopicsPosts: 'Topics/Posts',
    LastPost: 'Last Post',
    Topics: 'Topics',
    Posts: 'Posts',
    Close: "Close",
    NewForum: "New Forum",
    Confirm: 'Confirm',
    Delete: 'Delete',
    Cancel: 'Cancel',
    Forum: 'Forum',
    EditForum: 'Edit Forum',
    TitleRequired: 'Title is required',
    DescriptionRequired: 'Description is required',
    ForumName: 'Forum Title',
    ForumDescription: 'Forum Description',
    Delete: 'Delete',
    Save: 'Save',
    Add: 'Add',
    Update: 'Update',
    ConfirmDelete: 'Are you sure you want to delete the',
    Wait: "Wait...",
    Loading: 'Loading...',
    MessageRequired: 'Message is required',
    RepliesViews: 'Replies/Views',
    Replies: 'Replies',
    Views: 'Views',
    NewTopic: 'New Topic',
    TopicName: 'Topic Subject',
    TopicMessage: 'Topic Message',
    Topic: 'Topic',
    By: 'By',
    Forums: 'Forums',
    ExpirationDate: 'Expiration Date',
    Day: 'Day',
    Month: 'Month',
    Year: 'Year',
    PostName: 'Post Subject',
    PostContent: 'Post Content',
    SubjectRequired: 'Subject is required',
    ContentRequired: 'Content is required',
    EditPost: 'Edit Post',
    ReplyPost: 'Reply Post',
    EditTopic: 'Edit Topic',
    Undo: 'Undo',
    Redo: 'Redo',
    Post: 'Post',
    Answered: 'Answered',
    NotAnswered: 'Not Answered',
    LoadMore: "Load More",
    NewPosts: "New Post(s)"
  }
});
