name: Continue On Error
on:
  workflow_dispatch:   
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: echo "build"
    - name: test
      run: |
        echo "test"
        exit 1
    - name: report
      run: echo "report"
    
  
   
