name: Revealing secrets
on:
  workflow_dispatch:   
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - name: print username and password
      run: |
       echo ${{ secrets.ADMIN_USERNAME }}
       echo ${{ secrets.ADMIN_PASSWORD }}
   
    
  
   
